---
# See https://www.php.net/manual/en/info.configuration.php#ini.max-input-vars
- name: Adjust maximum amount of input variables that may be accepted
  lineinfile:
    dest: "/etc/php/7.3/fpm/pool.d/www.conf"
    regexp: "^php_admin_value\\[max_input_vars\\]"
    line: "php_admin_value[max_input_vars] = {{ php_admin_value.max_input_vars }}"
  notify: Restart php-fpm
  tags: php

- name: Adjust maximum amount of memory a script may consume
  lineinfile:
    dest: "/etc/php/7.3/fpm/pool.d/www.conf"
    regexp: "^php_admin_value\\[memory_limit\\]"
    line: "php_admin_value[memory_limit] = {{ php_admin_value.memory_limit }}"
  notify: Restart php-fpm
  tags: php
