---
- name: "Copy patches temporarily to server"
  copy:
    src: patches
    dest: /tmp
  tags: patch

# Reverse applied patches for git update not to fail. However, don′t force it—
# for a clean deployment′s sake!
# See https://stackoverflow.com/q/48167884/3375584
- name: "Reverse patches"
  shell:
    chdir: "{{ moodle_home }}"
    cmd: "git apply --reverse /tmp/patches/* || echo Already reversed"
  tags: patch

- name: "Check out Moodle {{ moodle_version }} for {{ moodle_instance | upper() }} instance"
  git:
    accept_hostkey: yes
    repo: "{{ moodle_repo }}"
    version: "{{ moodle_version }}"
    dest: "{{ moodle_home }}"
    update: yes
    force: "{{ git_force | default('no') }}"
  tags: checkout

- name: "Create configuration file for {{ moodle_instance | upper() }} instance"
  template:
    src: config.php.j2
    dest: "{{ moodle_home }}/config.php"
  tags: config

- name: "Apply patches"
  shell:
    chdir: "{{ moodle_home }}"
    cmd: git apply /tmp/patches/*
  tags: patch

- name: "Delete patches from server"
  file:
    dest: /tmp/patches
    state: absent
  tags: patch
