# See https://securitytxt.org/

- name: Delete wrong placed .well-known file(s)
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ moodle_home }}/.well-known"
    - "{{ document_root }}/.well-known/security.txt.j2"

- name: Create .well-known folder
  file:
    dest: "{{ document_root }}/.well-known"
    mode: 0755
    state: directory

- name: Copy security.txt template
  template:
    src: security.txt.j2
    dest: "{{ document_root }}/.well-known/security.txt"
    mode: 0644
