---
# Playbook to deploy Moodle on a server farm

- hosts: primary
  gather_facts: no

  pre_tasks:
    - name: Turn maintenance mode on
      shell:
        chdir: "{{ moodle_home }}"
        cmd: "/usr/bin/php admin/cli/maintenance.php --enableold"
      become_user: "{{ moodle_user }}"
      tags: [ maintenance, maintenanceon ]

- hosts: webservers
  gather_facts: no

  roles:
    - php

- hosts: all
  gather_facts: no

#  vars_prompt:
#    # See FORTHEM plug-in repo
#    - name: gitlabcom_username
#      prompt: "What is your GitLab.com username?"
#      private: no
#    - name: gitlabcom_password
#      prompt: "What is your GitLab.com password?"
#      private: yes

  roles:
    - prerequisites
    - sessions
    - moodle
    - plugins
    - securitytxt

- hosts: primary
  gather_facts: no
  become_user: "{{ moodle_user }}"
  
  tasks:
    - name: "Perform upgrade of Moodle to version {{ moodle_version }} for {{ moodle_instance | upper() }} instance"
      shell:
        chdir: "{{ moodle_home }}"
        cmd: "/usr/bin/php admin/cli/upgrade.php --lang=en --non-interactive --verbose-settings"
      tags: [ upgradeonly ]

- hosts: all
  gather_facts: no

  roles:
    - caches

- hosts: primary
  gather_facts: no

  post_tasks:
    - name: Turn maintenance mode off
      shell:
        chdir: "{{ moodle_home }}"
        cmd: "/usr/bin/php admin/cli/maintenance.php --disable"
      become_user: "{{ moodle_user }}"
      tags: [ maintenance, maintenanceoff ]
