---
# Playbook to deploy Moodle on a server farm

- hosts: webservers
  gather_facts: no
  roles:
    - php

- hosts: all
  gather_facts: no
  roles:
    - prerequisites
    - moodle
    - caches
    - securitytxt
