---
# Playbook to deploy Moodle on a server farm

- hosts: webservers
  gather_facts: no

  roles:
    - php

- hosts: all
  gather_facts: no

#  vars_prompt:
#    # See FORTHEM plug-in repo
#    - name: gitlabcom_username
#      prompt: "What is your GitLab.com username?"
#      private: no
#    - name: gitlabcom_password
#      prompt: "What is your GitLab.com password?"
#      private: yes

  roles:
    - prerequisites
    - moodle
    - caches
    - securitytxt
